// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditChainHead = `-- name: AuditChainHead :one
SELECT seq, hash FROM audit_events WHERE chain = $1 ORDER BY seq DESC LIMIT 1
`

type AuditChainHeadRow struct {
	Seq  int64
	Hash []byte
}

func (q *Queries) AuditChainHead(ctx context.Context, chain string) (AuditChainHeadRow, error) {
	row := q.db.QueryRow(ctx, auditChainHead, chain)
	var i AuditChainHeadRow
	err := row.Scan(&i.Seq, &i.Hash)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events
  (chain, seq, ts, actor_id, actor_type, system_admin, action, target_type, target_id, org_id, outcome, detail, prev_hash, hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
`

type InsertAuditEventParams struct {
	Chain       string
	Seq         int64
	Ts          pgtype.Timestamptz
	ActorID     string
	ActorType   string
	SystemAdmin bool
	Action      string
	TargetType  string
	TargetID    string
	OrgID       string
	Outcome     string
	Detail      []byte
	PrevHash    []byte
	Hash        []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.Chain,
		arg.Seq,
		arg.Ts,
		arg.ActorID,
		arg.ActorType,
		arg.SystemAdmin,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.OrgID,
		arg.Outcome,
		arg.Detail,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT seq, ts, actor_id, actor_type, system_admin, action, target_type, target_id, org_id, outcome, detail
FROM audit_events
WHERE chain = $1
  AND ($2::text = '' OR actor_id = $2)
  AND ($3::text = '' OR action = $3)
  AND ($4::text = '' OR outcome = $4)
  AND ts >= $5 AND ts <= $6
  AND seq > $7
ORDER BY ts DESC, seq DESC
LIMIT $8
`

type ListAuditEventsParams struct {
	Chain   string
	Column2 string
	Column3 string
	Column4 string
	Ts      pgtype.Timestamptz
	Ts_2    pgtype.Timestamptz
	Seq     int64
	Limit   int32
}

type ListAuditEventsRow struct {
	Seq         int64
	Ts          pgtype.Timestamptz
	ActorID     string
	ActorType   string
	SystemAdmin bool
	Action      string
	TargetType  string
	TargetID    string
	OrgID       string
	Outcome     string
	Detail      []byte
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Chain,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Ts,
		arg.Ts_2,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.ActorID,
			&i.ActorType,
			&i.SystemAdmin,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.OrgID,
			&i.Outcome,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanAuditChain = `-- name: ScanAuditChain :many
SELECT seq, ts, actor_id, actor_type, system_admin, action, target_type, target_id, org_id, outcome, detail, prev_hash, hash
FROM audit_events WHERE chain = $1 ORDER BY seq
`

type ScanAuditChainRow struct {
	Seq         int64
	Ts          pgtype.Timestamptz
	ActorID     string
	ActorType   string
	SystemAdmin bool
	Action      string
	TargetType  string
	TargetID    string
	OrgID       string
	Outcome     string
	Detail      []byte
	PrevHash    []byte
	Hash        []byte
}

func (q *Queries) ScanAuditChain(ctx context.Context, chain string) ([]ScanAuditChainRow, error) {
	rows, err := q.db.Query(ctx, scanAuditChain, chain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanAuditChainRow
	for rows.Next() {
		var i ScanAuditChainRow
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.ActorID,
			&i.ActorType,
			&i.SystemAdmin,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.OrgID,
			&i.Outcome,
			&i.Detail,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
