// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	Chain       string
	Seq         int64
	Ts          pgtype.Timestamptz
	ActorID     string
	ActorType   string
	SystemAdmin bool
	Action      string
	TargetType  string
	TargetID    string
	OrgID       string
	Outcome     string
	Detail      []byte
	PrevHash    []byte
	Hash        []byte
}

type Delegation struct {
	ID                   pgtype.UUID
	AgentPrincipalID     string
	DelegatorPrincipalID string
	OrgID                pgtype.UUID
	Scope                []string
	CnfJkt               string
	ParentDelegationID   pgtype.UUID
	ExpiresAt            pgtype.Timestamptz
	Revoked              bool
	CreatedAt            pgtype.Timestamptz
}

type Membership struct {
	PrincipalID string
	OrgID       pgtype.UUID
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	ParentID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Ownership struct {
	ResourceType     string
	ResourceID       string
	OwnerPrincipalID string
	OrgID            pgtype.UUID
}

type Principal struct {
	ID               string
	Type             string
	DisplayName      string
	OwnerPrincipalID pgtype.Text
	Capabilities     []string
	Purpose          string
	OnBehalfOf       string
	CreatedAt        pgtype.Timestamptz
}

type Role struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	Name        string
	Permissions []string
}

type RoleAssignment struct {
	PrincipalID string
	RoleID      pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.UUID
}

type SigningKey struct {
	Kid         string
	Alg         string
	PrivateEnc  []byte
	State       string
	CreatedAt   pgtype.Timestamptz
	RetireAfter pgtype.Timestamptz
}

type Team struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
	Name  string
}

type TeamMembership struct {
	PrincipalID string
	TeamID      pgtype.UUID
}
