// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM role_assignments ra
    JOIN roles r ON r.id = ra.role_id
    WHERE ra.principal_id = $1
      AND ( $2::text = ANY(r.permissions) OR '*' = ANY(r.permissions) )
      AND (
            (ra.scope_type = 'org'  AND ra.scope_id = $3)
         OR (ra.scope_type = 'team' AND ra.scope_id = $4)
      )
) AS allowed
`

type HasPermissionParams struct {
	PrincipalID string
	Action      string
	OrgID       pgtype.UUID
	TeamID      pgtype.UUID
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission,
		arg.PrincipalID,
		arg.Action,
		arg.OrgID,
		arg.TeamID,
	)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const isOwner = `-- name: IsOwner :one
SELECT EXISTS (
    SELECT 1 FROM ownership
    WHERE resource_type = $1 AND resource_id = $2 AND owner_principal_id = $3
) AS is_owner
`

type IsOwnerParams struct {
	ResourceType     string
	ResourceID       string
	OwnerPrincipalID string
}

func (q *Queries) IsOwner(ctx context.Context, arg IsOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOwner, arg.ResourceType, arg.ResourceID, arg.OwnerPrincipalID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const registerOwnership = `-- name: RegisterOwnership :exec
INSERT INTO ownership (resource_type, resource_id, owner_principal_id, org_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (resource_type, resource_id)
DO UPDATE SET owner_principal_id = EXCLUDED.owner_principal_id, org_id = EXCLUDED.org_id
`

type RegisterOwnershipParams struct {
	ResourceType     string
	ResourceID       string
	OwnerPrincipalID string
	OrgID            pgtype.UUID
}

func (q *Queries) RegisterOwnership(ctx context.Context, arg RegisterOwnershipParams) error {
	_, err := q.db.Exec(ctx, registerOwnership,
		arg.ResourceType,
		arg.ResourceID,
		arg.OwnerPrincipalID,
		arg.OrgID,
	)
	return err
}
