// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikey.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveApiKeys = `-- name: CountActiveApiKeys :one
SELECT count(*) FROM api_keys
WHERE principal_id = $1 AND NOT revoked AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) CountActiveApiKeys(ctx context.Context, principalID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveApiKeys, principalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApiKey = `-- name: GetApiKey :one
SELECT key_id, principal_id, org_id, name, hash, hash_version, read_only, revoked, created_at, expires_at, last_used_at
FROM api_keys WHERE key_id = $1
`

func (q *Queries) GetApiKey(ctx context.Context, keyID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKey, keyID)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.PrincipalID,
		&i.OrgID,
		&i.Name,
		&i.Hash,
		&i.HashVersion,
		&i.ReadOnly,
		&i.Revoked,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertApiKey = `-- name: InsertApiKey :exec
INSERT INTO api_keys (key_id, principal_id, org_id, name, hash, read_only, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertApiKeyParams struct {
	KeyID       string
	PrincipalID string
	OrgID       string
	Name        string
	Hash        []byte
	ReadOnly    bool
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error {
	_, err := q.db.Exec(ctx, insertApiKey,
		arg.KeyID,
		arg.PrincipalID,
		arg.OrgID,
		arg.Name,
		arg.Hash,
		arg.ReadOnly,
		arg.ExpiresAt,
	)
	return err
}

const listApiKeysByPrincipal = `-- name: ListApiKeysByPrincipal :many
SELECT key_id, principal_id, org_id, name, hash, hash_version, read_only, revoked, created_at, expires_at, last_used_at
FROM api_keys
WHERE principal_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC, key_id DESC
LIMIT $3
`

type ListApiKeysByPrincipalParams struct {
	PrincipalID string
	Column2     pgtype.Timestamptz
	Limit       int32
}

func (q *Queries) ListApiKeysByPrincipal(ctx context.Context, arg ListApiKeysByPrincipalParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByPrincipal, arg.PrincipalID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.KeyID,
			&i.PrincipalID,
			&i.OrgID,
			&i.Name,
			&i.Hash,
			&i.HashVersion,
			&i.ReadOnly,
			&i.Revoked,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys SET revoked = true WHERE key_id = $1
RETURNING key_id, principal_id, org_id, name, hash, hash_version, read_only, revoked, created_at, expires_at, last_used_at
`

func (q *Queries) RevokeApiKey(ctx context.Context, keyID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, keyID)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.PrincipalID,
		&i.OrgID,
		&i.Name,
		&i.Hash,
		&i.HashVersion,
		&i.ReadOnly,
		&i.Revoked,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchApiKeyLastUsed = `-- name: TouchApiKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now()
WHERE key_id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchApiKeyLastUsed(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, touchApiKeyLastUsed, keyID)
	return err
}
