// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signingkey.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSigningKeys = `-- name: DeleteExpiredSigningKeys :execrows
DELETE FROM signing_keys WHERE state = 'retiring' AND retire_after < now()
`

func (q *Queries) DeleteExpiredSigningKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSigningKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const demoteActiveSigningKey = `-- name: DemoteActiveSigningKey :exec
UPDATE signing_keys SET state = 'retiring', retire_after = $1 WHERE state = 'active'
`

func (q *Queries) DemoteActiveSigningKey(ctx context.Context, retireAfter pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, demoteActiveSigningKey, retireAfter)
	return err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, alg, private_enc, state, retire_after
FROM signing_keys WHERE state = 'active'
`

type GetActiveSigningKeyRow struct {
	Kid         string
	Alg         string
	PrivateEnc  []byte
	State       string
	RetireAfter pgtype.Timestamptz
}

func (q *Queries) GetActiveSigningKey(ctx context.Context) (GetActiveSigningKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i GetActiveSigningKeyRow
	err := row.Scan(
		&i.Kid,
		&i.Alg,
		&i.PrivateEnc,
		&i.State,
		&i.RetireAfter,
	)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :exec
INSERT INTO signing_keys (kid, alg, private_enc, state, retire_after)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSigningKeyParams struct {
	Kid         string
	Alg         string
	PrivateEnc  []byte
	State       string
	RetireAfter pgtype.Timestamptz
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) error {
	_, err := q.db.Exec(ctx, insertSigningKey,
		arg.Kid,
		arg.Alg,
		arg.PrivateEnc,
		arg.State,
		arg.RetireAfter,
	)
	return err
}

const listLiveSigningKeys = `-- name: ListLiveSigningKeys :many
SELECT kid, alg, private_enc, state, retire_after
FROM signing_keys WHERE state IN ('active', 'retiring')
ORDER BY created_at
`

type ListLiveSigningKeysRow struct {
	Kid         string
	Alg         string
	PrivateEnc  []byte
	State       string
	RetireAfter pgtype.Timestamptz
}

func (q *Queries) ListLiveSigningKeys(ctx context.Context) ([]ListLiveSigningKeysRow, error) {
	rows, err := q.db.Query(ctx, listLiveSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveSigningKeysRow
	for rows.Next() {
		var i ListLiveSigningKeysRow
		if err := rows.Scan(
			&i.Kid,
			&i.Alg,
			&i.PrivateEnc,
			&i.State,
			&i.RetireAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
