// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Principal struct {
	ID               string
	Type             string
	DisplayName      string
	OwnerPrincipalID pgtype.Text
	Capabilities     []string
	Purpose          string
	OnBehalfOf       string
	CreatedAt        pgtype.Timestamptz
}
