// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, type, display_name, owner_principal_id, capabilities, purpose, on_behalf_of
FROM principals WHERE id = $1
`

type GetPrincipalRow struct {
	ID               string
	Type             string
	DisplayName      string
	OwnerPrincipalID pgtype.Text
	Capabilities     []string
	Purpose          string
	OnBehalfOf       string
}

func (q *Queries) GetPrincipal(ctx context.Context, id string) (GetPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getPrincipal, id)
	var i GetPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DisplayName,
		&i.OwnerPrincipalID,
		&i.Capabilities,
		&i.Purpose,
		&i.OnBehalfOf,
	)
	return i, err
}

const insertPrincipal = `-- name: InsertPrincipal :exec
INSERT INTO principals (id, type, display_name, owner_principal_id, capabilities, purpose, on_behalf_of)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPrincipalParams struct {
	ID               string
	Type             string
	DisplayName      string
	OwnerPrincipalID pgtype.Text
	Capabilities     []string
	Purpose          string
	OnBehalfOf       string
}

func (q *Queries) InsertPrincipal(ctx context.Context, arg InsertPrincipalParams) error {
	_, err := q.db.Exec(ctx, insertPrincipal,
		arg.ID,
		arg.Type,
		arg.DisplayName,
		arg.OwnerPrincipalID,
		arg.Capabilities,
		arg.Purpose,
		arg.OnBehalfOf,
	)
	return err
}
