// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDelegation = `-- name: GetDelegation :one
SELECT id, agent_principal_id, delegator_principal_id, org_id, scope, cnf_jkt, expires_at, revoked
FROM delegations WHERE id = $1
`

type GetDelegationRow struct {
	ID                   pgtype.UUID
	AgentPrincipalID     string
	DelegatorPrincipalID string
	OrgID                pgtype.UUID
	Scope                []string
	CnfJkt               string
	ExpiresAt            pgtype.Timestamptz
	Revoked              bool
}

func (q *Queries) GetDelegation(ctx context.Context, id pgtype.UUID) (GetDelegationRow, error) {
	row := q.db.QueryRow(ctx, getDelegation, id)
	var i GetDelegationRow
	err := row.Scan(
		&i.ID,
		&i.AgentPrincipalID,
		&i.DelegatorPrincipalID,
		&i.OrgID,
		&i.Scope,
		&i.CnfJkt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const insertDelegation = `-- name: InsertDelegation :one
INSERT INTO delegations (agent_principal_id, delegator_principal_id, org_id, scope, cnf_jkt, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertDelegationParams struct {
	AgentPrincipalID     string
	DelegatorPrincipalID string
	OrgID                pgtype.UUID
	Scope                []string
	CnfJkt               string
	ExpiresAt            pgtype.Timestamptz
}

func (q *Queries) InsertDelegation(ctx context.Context, arg InsertDelegationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDelegation,
		arg.AgentPrincipalID,
		arg.DelegatorPrincipalID,
		arg.OrgID,
		arg.Scope,
		arg.CnfJkt,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeDelegation = `-- name: RevokeDelegation :execrows
UPDATE delegations SET revoked = true WHERE id = $1
`

func (q *Queries) RevokeDelegation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDelegation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
