// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO role_assignments (principal_id, role_id, scope_type, scope_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (principal_id, role_id, scope_type, scope_id) DO NOTHING
`

type AssignRoleParams struct {
	PrincipalID string
	RoleID      pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.UUID
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole,
		arg.PrincipalID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
	)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (org_id, name, permissions) VALUES ($1, $2, $3)
RETURNING id, org_id, name, permissions
`

type CreateRoleParams struct {
	OrgID       pgtype.UUID
	Name        string
	Permissions []string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.OrgID, arg.Name, arg.Permissions)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Permissions,
	)
	return i, err
}

const getRoleOrg = `-- name: GetRoleOrg :one
SELECT org_id FROM roles WHERE id = $1
`

func (q *Queries) GetRoleOrg(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRoleOrg, id)
	var org_id pgtype.UUID
	err := row.Scan(&org_id)
	return org_id, err
}

const getTeamOrg = `-- name: GetTeamOrg :one
SELECT org_id FROM teams WHERE id = $1
`

func (q *Queries) GetTeamOrg(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTeamOrg, id)
	var org_id pgtype.UUID
	err := row.Scan(&org_id)
	return org_id, err
}
