// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :exec
INSERT INTO memberships (principal_id, org_id) VALUES ($1, $2)
ON CONFLICT (principal_id, org_id) DO NOTHING
`

type AddMemberParams struct {
	PrincipalID string
	OrgID       pgtype.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.PrincipalID, arg.OrgID)
	return err
}

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_memberships (principal_id, team_id) VALUES ($1, $2)
ON CONFLICT (principal_id, team_id) DO NOTHING
`

type AddTeamMemberParams struct {
	PrincipalID string
	TeamID      pgtype.UUID
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.PrincipalID, arg.TeamID)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organizations (name) VALUES ($1) RETURNING id, name, COALESCE(parent_id::text, '') AS parent_id
`

type CreateOrgRow struct {
	ID       pgtype.UUID
	Name     string
	ParentID interface{}
}

func (q *Queries) CreateOrg(ctx context.Context, name string) (CreateOrgRow, error) {
	row := q.db.QueryRow(ctx, createOrg, name)
	var i CreateOrgRow
	err := row.Scan(&i.ID, &i.Name, &i.ParentID)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, name) VALUES ($1, $2) RETURNING id, org_id, name
`

type CreateTeamParams struct {
	OrgID pgtype.UUID
	Name  string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.OrgID, arg.Name)
	var i Team
	err := row.Scan(&i.ID, &i.OrgID, &i.Name)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, COALESCE(parent_id::text, '') AS parent_id FROM organizations WHERE id = $1
`

type GetOrgRow struct {
	ID       pgtype.UUID
	Name     string
	ParentID interface{}
}

func (q *Queries) GetOrg(ctx context.Context, id pgtype.UUID) (GetOrgRow, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i GetOrgRow
	err := row.Scan(&i.ID, &i.Name, &i.ParentID)
	return i, err
}
